---

- hosts: archlinux

  tasks:
    - name: Create the 'aur_builder' user 
      become: yes
      user: 
        name: aur_builder
        shell: /usr/bin/nologin
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'


    - name: Install paru using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: paru
        use: makepkg
        state: present
      become: yes
      become_user: aur_builder

    - name: Install kopia and kopia_ui using paru
      kewlfft.aur.aur:
        use: paru
        name:
          - kopia
          - kopia-ui-bin
        state: present
      become: yes
      become_user: aur_builder

    # Note: Dependency resolution will still include repository packages.
    - name: Upgrade the system using paru, only act on AUR packages.
      kewlfft.aur.aur:
        upgrade: yes
        use: paru
        aur_only: yes
